BaSP-MR-95: Subscriptions routes and forms
BaSP-m2023/joaco-megarocket-app pull request #33
Opened 2023-06-09 19:25 UTC by JuanManuel-Blois

Added subscriptions routes and updated the form component

2023-06-09 20:08 UTC, Tilajc commented on src/Components/Subscriptions/FormSubscriptions/index.js
> +          isConfirm: false
You don't need it any more

2023-06-09 20:08 UTC, Tilajc commented on src/Components/Subscriptions/FormSubscriptions/index.js
> +          isConfirm: false
```suggestion
         
```

2023-06-09 20:09 UTC, Tilajc commented on src/Components/Subscriptions/FormSubscriptions/index.js
> +        isConfirm: false
you don't need it any more
```suggestion
        
```

2023-06-09 20:10 UTC, Tilajc commented on src/Components/Subscriptions/FormSubscriptions/index.js
> +        confirmModal={responseModal.isConfirm}
you don't need it any more
```suggestion
        
```

2023-06-09 20:14 UTC, Tilajc requested changes
well done! I left a little comments

2023-06-09 20:16 UTC, LucianoStradiot commented
![](https://github.trello.services/images/mini-trello-icon.png) [Form Components - Subscription](https://trello.com/c/m5TVTXhH/95-form-components-subscription)

2023-06-09 20:53 UTC, Tilajc approved these changes
Good Job!

2023-06-09 21:58 UTC, merged

2023-06-10 21:51 UTC, Katairala commented
Tested locally on https://joaco-megarocket-app.vercel.app/
Test Results: Passed 🌟

It looks really nice! Great work Juan Manuel!