BaSP-MR-114: activities redux
BaSP-m2023/joaco-megarocket-app pull request #46
Opened 2023-06-13 17:17 UTC by LucianoStradiot

Implement redux on activities entity

2023-06-13 20:49 UTC, Tilajc commented on src/Components/Activities/FormActivity/index.js
> +  /* const getActivities = async () => {
you can delete the commented lines
```suggestion

```

2023-06-13 21:27 UTC, Tilajc commented on src/Redux/Activities/reducer.js
> +        data: state.data.filter((activity) => activity._id !== action.payload.id),
```suggestion
        data: state.data.filter((activity) => activity._id !== action.payload._id),
```

2023-06-13 21:44 UTC, Tilajc requested changes
I leave some comments, good job!

2023-06-13 21:52 UTC, Tilajc approved these changes
Good job!

2023-06-13 21:53 UTC, merged

2023-06-13 23:25 UTC, LucianoStradiot commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implement Redux on the Activities entity](https://trello.com/c/koE2LRu6/114-implement-redux-on-the-activities-entity)

2023-06-14 18:22 UTC, Katairala commented
Tested locally on https://joaco-megarocket-app.vercel.app/
Test Results: Passed 💯 

It great! Nice work Luciano