BaSP-MR-108: Implementation redux in admins
BaSP-m2023/joaco-megarocket-app pull request #47
Opened 2023-06-13 17:25 UTC by Eugeniagassman

implement redux in admin, creating the thunks, reducer, constants, and actions files.
 in this implementation the get, put, post, and delete methods are executed.

2023-06-13 21:56 UTC, Tilajc commented on src/Components/Admins/Form/index.js
> +      console.log('data', data);
you can delete this console.log
```suggestion

```

2023-06-13 22:14 UTC, Tilajc commented on src/Redux/Admins/actions.js
> +export const putAdminsSuccess = (updAdmin) => {
here when you add an id the response will be correct
```suggestion
export const putAdminsSuccess = (updAdmin, id) => {
```

2023-06-13 22:14 UTC, Tilajc commented on src/Redux/Admins/actions.js
> +    payload: updAdmin
same here, you need the id
```suggestion
    payload: updAdmin, id
```

2023-06-13 22:15 UTC, Tilajc commented on src/Redux/Admins/reducer.js
> +      const idDeletedAdmin = [action.payload.id];
the ID without _ is undefined
```suggestion
      const idDeletedAdmin = [action.payload._id];
```

2023-06-13 22:16 UTC, Tilajc commented on src/Redux/Admins/reducer.js
> +      const currentAdmins = state.data.filter((admins) => admins.id !== idDeletedAdmin);
same here
```suggestion
      const currentAdmins = state.data.filter((admins) => admins._id !== idDeletedAdmin);
```

2023-06-13 22:17 UTC, Tilajc requested changes
well done! just a little changes

2023-06-13 22:18 UTC, Tilajc commented
I don't know how to made a comment when you didn't make any change there, but in the form index, into the html, you need to call the spinner too

2023-06-13 23:00 UTC, Eugeniagassman commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implement Redux on the Admins entity](https://trello.com/c/yQkwiK9d/108-implement-redux-on-the-admins-entity)

2023-06-13 23:22 UTC, Tilajc approved these changes
Good job!

2023-06-13 23:23 UTC, merged

2023-06-15 01:44 UTC, Flor-Farruggia commented
Nice job!