BaSP-MR-112: implement redux subscription
BaSP-m2023/joaco-megarocket-app pull request #48
Opened 2023-06-13 21:54 UTC by GaloDurante

I worked adding Redux on the subscriptions resource and implement a Spinner when the page is loading

2023-06-13 23:30 UTC, LucianoStradiot commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implement Redux on the Subscriptions entity](https://trello.com/c/3gtwy2aB/112-implement-redux-on-the-subscriptions-entity)

2023-06-14 02:32 UTC, Tilajc commented on src/Components/Subscriptions/index.js
> +  //const [subscriptions, setSubscriptions] = useState([]);
You can delete this
```suggestion
  
```

2023-06-14 02:37 UTC, Tilajc requested changes
Pretty good job, just delete the comment!

2023-06-14 02:38 UTC, Tilajc approved these changes
gj

2023-06-14 02:39 UTC, merged

2023-06-14 18:15 UTC, Katairala commented
Tested locally on https://joaco-megarocket-app.vercel.app/
Test Results: Passed 🌟

It looks great Galo!