BaSP-MR-113: redux on members.
BaSP-m2023/joaco-megarocket-app pull request #49
Opened 2023-06-13 23:30 UTC by Franro212

Implementation of Redux in members component.
Implementation of spiner in form and index.

2023-06-13 23:58 UTC, LucianoStradiot commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implement Redux on the Members entity](https://trello.com/c/7HDOkTzq/113-implement-redux-on-the-members-entity)

2023-06-14 00:12 UTC, Tilajc commented on src/Redux/Members/reducer.js
> +        data: state.data.filter((member) => member._id !== action.payload.id),
the id without _ is undefined
```suggestion
        data: state.data.filter((member) => member._id !== action.payload._id),
```

2023-06-14 00:32 UTC, Tilajc commented on src/Redux/Members/constants.js
> +export const PUT_MEMBERS_PENDING = 'PUT_MEMBERS_ERROR';
there is an infinite spinner loop
```suggestion
export const PUT_MEMBERS_PENDING = 'PUT_MEMBERS_PENDING';
```

2023-06-14 00:39 UTC, Tilajc commented on src/Components/Members/FormMembers/index.js
You need to validate the response and when the response is OK you should go back to the list, and when it's !OK should remain in the page

2023-06-14 00:45 UTC, Tilajc commented on src/Redux/Members/reducer.js
> +          member._id === action.payload.id ? action.payload : member
```suggestion
          member._id === action.id ? action.payload : member
```

2023-06-14 00:47 UTC, Tilajc requested changes
I leave some comments Good job!

2023-06-14 01:36 UTC, Franro212 commented on src/Redux/Members/reducer.js
> +        data: state.data.filter((member) => member._id !== action.payload.id),
done

2023-06-14 01:36 UTC, Franro212 commented on src/Redux/Members/constants.js
> +export const PUT_MEMBERS_PENDING = 'PUT_MEMBERS_ERROR';
donde

2023-06-14 01:36 UTC, Franro212 commented on src/Components/Members/FormMembers/index.js
done

2023-06-14 01:36 UTC, Franro212 commented on src/Redux/Members/reducer.js
> +          member._id === action.payload.id ? action.payload : member
done

2023-06-14 01:46 UTC, Tilajc approved these changes
Well done!

2023-06-14 01:54 UTC, merged

2023-06-14 16:11 UTC, LautaroVercellini commented
Works Good!